[package]
name = "rust-forms-db-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = {version = "0.30.0"}
lazy_static = "1.4.0"
cargo-watch = "8.4.1"
